project:
  type: website
  output-dir: docs
  resources:
    - assets/**
    - data/**

website:
  favicon: "images/Logo_Favicon.ico"
  page-footer:
    left: "© 2025 ClimeApp Team – University of Bern"
    right: |
      This page is built with [Quarto](https://quarto.org/)

  navbar:
    logo: images/Logo.png
    title: Tutorials
    tools:
      - icon: github
        href: https://github.com/ClimeApp

format:
  html:
    css: styles.css
    toc: true
    toc-location: left
